name: to_do_list
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ---------------- Image Assets ----------------
  assets:
    - assets/images/landing_image.png
